version: '3'
services:
  config-service:
    build: config-service
    ports:
      - 8888:8888

  registry:
    build: registry

  api-gateway:
    build: api-gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6000:6000

#  recognition-service:
#    build: recognition-service
#    ports:
#      - "7000:7000"
#
#  number-plate-service:
#      build: number-plate-service
#      ports:
#        - 8000:8000

  web-ui-service:
      build: web-ui-service
      ports:
        - 9000:9000

  common-mongodb:
    build: mongodb
    ports:
      - 26000:27017
