version: '2'
services:
  config-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    image: maxclay/transport-video-search-system-config-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    image: maxclay/transport-video-search-system-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  api-gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    image: maxclay/transport-video-search-system-api-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      NOTIFICATION_SERVICE_PASSWORD: ${NOTIFICATION_SERVICE_PASSWORD}
      STATISTICS_SERVICE_PASSWORD: ${STATISTICS_SERVICE_PASSWORD}
      ACCOUNT_SERVICE_PASSWORD: ${ACCOUNT_SERVICE_PASSWORD}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    image: maxclay/transport-video-search-system-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    image: maxclay/transport-video-search-system-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      ACCOUNT_SERVICE_PASSWORD: ${ACCOUNT_SERVICE_PASSWORD}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    image: maxclay/transport-video-search-system-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    image: maxclay/transport-video-search-system-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        