hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /auth-service/**
        url: http://localhost:5000
        stripPrefix: false
        sensitiveHeaders:
    account-service:
            path: /account-service/**
            serviceId: account-service
            stripPrefix: false
            sensitiveHeaders:
    recognition-service:
            path: /recognition-service/**
            serviceId: recognition-service
            stripPrefix: false
            sensitiveHeaders:
    number-plate-service:
                path: /number-plate-service/**
                serviceId: number-plate-service
                stripPrefix: false
                sensitiveHeaders:

spring:
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB

server:
  port: 4000
